package moore_stateMachine.sandbox;

/*Generated by MPS */


public class Main {
  public static void main(String[] args) {
    System.out.println("Executing lightSwitch Mealy FSM");
    LighSwitch fsm = new LighSwitch();
    fsm.displayState();
    fsm.onEvent(0);
    fsm.onEvent(1);
    fsm.onEvent(0);
    fsm.onEvent(0);
    fsm.onEvent(0);
    fsm.onEvent(1);
    fsm.displayState();
  }
}
