package mealyFSM.sandbox;

/*Generated by MPS */


public class lightSwitch {


  private final int LIGHTOFF = 0;
  private final int LIGHTONDIM = 1;
  private final int LIGHTONMEDIUM = 2;
  private final int LIGHTONBRIGHT = 3;
  private final int ONPRESSED = 0;
  private final int OFFPRESSED = 1;
  private final int BRIGHTNESSOFF = 0;
  private final int BRIGHTNESSDIM = 1;
  private final int BRIGHTNESSMEDIUM = 2;
  private final int BRIGHTNESSHIGH = 3;


  private int currentState = LIGHTOFF;

  public lightSwitch() {
  }

  public void displayState() {
    String stateName = "";
    switch (currentState) {
      case LIGHTOFF:
        System.out.println("Current State: " + "lightOff");
        break;
      case LIGHTONDIM:
        System.out.println("Current State: " + "lightONdim");
        break;
      case LIGHTONMEDIUM:
        System.out.println("Current State: " + "lightONmedium");
        break;
      case LIGHTONBRIGHT:
        System.out.println("Current State: " + "lightONbright");
        break;
    }
  }

  public void onEvent(int event) {
    switch (currentState) {
      case LIGHTOFF:
        switch (event) {
          case ONPRESSED:
            System.out.println("  On Event: " + "onPressed" + " moved to State: " + "lightONdim" + " with action " + "brightnessDim");
            this.currentState = LIGHTONDIM;
            break;
        }
        break;
      case LIGHTONDIM:
        switch (event) {
          case OFFPRESSED:
            System.out.println("  On Event: " + "offPressed" + " moved to State: " + "lightOff" + " with action " + "brightnessOFF");
            this.currentState = LIGHTOFF;
            break;
          case ONPRESSED:
            System.out.println("  On Event: " + "onPressed" + " moved to State: " + "lightONmedium" + " with action " + "brightnessMedium");
            this.currentState = LIGHTONMEDIUM;
            break;
        }
        break;
      case LIGHTONMEDIUM:
        switch (event) {
          case OFFPRESSED:
            System.out.println("  On Event: " + "offPressed" + " moved to State: " + "lightOff" + " with action " + "brightnessOFF");
            this.currentState = LIGHTOFF;
            break;
          case ONPRESSED:
            System.out.println("  On Event: " + "onPressed" + " moved to State: " + "lightONbright" + " with action " + "brightnessHigh");
            this.currentState = LIGHTONBRIGHT;
            break;
        }
        break;
      case LIGHTONBRIGHT:
        switch (event) {
          case OFFPRESSED:
            System.out.println("  On Event: " + "offPressed" + " moved to State: " + "lightOff" + " with action " + "brightnessOFF");
            this.currentState = LIGHTOFF;
            break;
          case ONPRESSED:
            System.out.println("  On Event: " + "onPressed" + " moved to State: " + "lightONdim" + " with action " + "brightnessDim");
            this.currentState = LIGHTONDIM;
            break;
        }
        break;
    }
  }

}
