package mealyFSM.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int StateMachine = 0;
  public static final int action = 1;
  public static final int event = 2;
  public static final int state = 3;
  public static final int transition = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xdc97585e752a461cL, 0x8b396a0782f6bf23L);
    builder.put(0x350e7bfe0ac9d0b1L, StateMachine);
    builder.put(0x350e7bfe0ac9d0b0L, action);
    builder.put(0x350e7bfe0ac9d0afL, event);
    builder.put(0x350e7bfe0ac9d0adL, state);
    builder.put(0x350e7bfe0ac9d0aeL, transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
