package moore_stateMachine.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int Event = 1;
  public static final int State = 2;
  public static final int StateMachine = 3;
  public static final int Transition = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x37c2cb4348354f1dL, 0xb1474442de330b2cL);
    builder.put(0x25df9cb315087cf9L, Action);
    builder.put(0x25df9cb315079f49L, Event);
    builder.put(0x25df9cb315079f4cL, State);
    builder.put(0x25df9cb315066ad0L, StateMachine);
    builder.put(0x25df9cb315079f4fL, Transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
