package mealyFSM.sandbox;

/*Generated by MPS */


public class Main {
  public static void main(String[] args) {
    System.out.println("Executing lightSwitch Mealy FSM");
    lightSwitch fsm = new lightSwitch();
    fsm.displayState();
    fsm.onEvent(0);
    fsm.onEvent(1);
    fsm.onEvent(0);
    fsm.onEvent(0);
    fsm.onEvent(0);
    fsm.onEvent(1);
    fsm.displayState();
  }
}
