mmult: src/mmult.c
	gcc src/mmult.c -lpthread -o bin/mmult

mmult_3a: src/mmult_3a.c
	gcc src/mmult_3a.c -lpthread -o bin/mmult_3a

mmult_3b: src/mmult_3b.c
	gcc src/mmult_3b.c -lpthread -o bin/mmult_3b

mmult_3c: src/mmult_3c.c
	gcc src/mmult_3c.c -lpthread -o bin/mmult_3c

quicksort: src/quick_sort.c
	gcc src/quick_sort.c -lpthread -o bin/quicksort

init:
	mkdir -p bin

clean:
	rm -rf bin/*